from __future__ import annotations

import http.cookiejar
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


AUTH_COOKIE_MODE = "软件内登录"
YOUTUBE_ACCOUNT_COOKIE_NAMES = {
    "SID",
    "HSID",
    "SSID",
    "APISID",
    "SAPISID",
    "__Secure-1PSID",
    "__Secure-3PSID",
    "__Secure-1PAPISID",
    "__Secure-3PAPISID",
}
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
)


def auth_data_dir() -> Path:
    if sys.platform == "darwin":
        base = Path.home() / "Library" / "Application Support"
    elif os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA", str(Path.home())))
    else:
        base = Path(os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local" / "share")))
    path = base / "NanzhufengVideoDownloader"
    path.mkdir(parents=True, exist_ok=True)
    return path


def auth_profile_dir(platform: str | None = None) -> Path:
    profile_name = f"browser-profile-{platform}" if platform in {"douyin", "youtube"} else "browser-profile"
    path = auth_data_dir() / profile_name
    path.mkdir(parents=True, exist_ok=True)
    return path


def auth_cookie_file() -> Path:
    return auth_data_dir() / "managed-cookies.txt"


def platform_cookie_file(platform: str) -> Path:
    return auth_data_dir() / f"managed-cookies-{platform}.txt"


def has_youtube_account_cookies(cookie_file: Path | None = None) -> bool:
    """判断软件内 Cookie 是否包含尚未过期的 YouTube 账号登录凭据。"""
    target = cookie_file or platform_cookie_file("youtube")
    if not target.exists():
        return False

    now = time.time()
    for line in target.read_text(encoding="utf-8", errors="ignore").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        domain, expires_text, name = parts[0].lower(), parts[4], parts[5]
        if "youtube.com" not in domain and "google.com" not in domain:
            continue
        if name not in YOUTUBE_ACCOUNT_COOKIE_NAMES:
            continue
        try:
            expires = int(expires_text or 0)
        except ValueError:
            continue
        if expires == 0 or expires > now:
            return True
    return False


def find_browser_path() -> str | None:
    candidates = [
        Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
        Path(r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"),
        Path(r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"),
        Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"),
        Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"),
        Path.home() / "Applications" / "Google Chrome.app" / "Contents" / "MacOS" / "Google Chrome",
        Path("/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge"),
        Path.home() / "Applications" / "Microsoft Edge.app" / "Contents" / "MacOS" / "Microsoft Edge",
        Path("/usr/bin/google-chrome"),
        Path("/usr/bin/chromium"),
        Path("/usr/bin/microsoft-edge"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return None


def _write_cookies_txt(cookies: list[dict[str, Any]], target: Path | None = None) -> Path:
    target = target or auth_cookie_file()
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Nanzhufeng Video Downloader",
    ]
    for item in cookies:
        domain = str(item.get("domain") or "")
        name = str(item.get("name") or "")
        value = str(item.get("value") or "")
        if not domain or not name:
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(item.get("path") or "/")
        secure = "TRUE" if item.get("secure") else "FALSE"
        raw_expires = item.get("expires")
        expires = str(int(raw_expires)) if raw_expires and float(raw_expires) > 0 else "0"
        lines.append("\t".join([domain, include_subdomains, path, secure, expires, name, value]))
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def _merge_cookie_files() -> Path:
    """合并各平台登录 Cookie，下载时统一读取这个文件。"""
    merged: dict[tuple[str, str, str], str] = {}
    header = [
        "# Netscape HTTP Cookie File",
        "# Generated by Nanzhufeng Video Downloader",
    ]
    platform_files = [platform_cookie_file("douyin"), platform_cookie_file("youtube")]
    sources = [source for source in platform_files if source.exists()]
    if not sources and auth_cookie_file().exists():
        sources = [auth_cookie_file()]

    for source in sources:
        if not source.exists():
            continue
        for line in source.read_text(encoding="utf-8", errors="ignore").splitlines():
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 7:
                continue
            try:
                if int(parts[4] or 0) < 0:
                    parts[4] = "0"
            except ValueError:
                parts[4] = "0"
            line = "\t".join(parts)
            key = (parts[0], parts[2], parts[5])
            merged[key] = line

    target = auth_cookie_file()
    target.write_text("\n".join(header + list(merged.values())) + "\n", encoding="utf-8")
    return target


def open_login_browser(platform: str) -> None:
    """打开软件独立登录窗口，关闭窗口后导出 Cookie 供后续读取/下载使用。"""
    from playwright.sync_api import sync_playwright

    browser_path = find_browser_path()
    if not browser_path:
        raise RuntimeError("没有找到 Chrome 或 Edge，无法打开软件内登录窗口。")

    platform_url = {
        "douyin": "https://www.douyin.com/",
        "youtube": "https://www.youtube.com/",
    }.get(platform)
    if not platform_url:
        raise RuntimeError("未知的登录平台。")

    with sync_playwright() as playwright:
        try:
            context = playwright.chromium.launch_persistent_context(
                user_data_dir=str(auth_profile_dir(platform)),
                executable_path=browser_path,
                headless=False,
                args=["--disable-blink-features=AutomationControlled"],
                viewport={"width": 1280, "height": 820},
                locale="zh-CN",
                user_agent=USER_AGENT,
            )
        except Exception as exc:
            if "Target page, context or browser has been closed" in str(exc):
                raise RuntimeError("软件内登录窗口已经在运行，或上一次登录窗口还没有完全关闭。请先关闭那个登录窗口后再试。") from exc
            raise
        first_page = context.pages[0] if context.pages else context.new_page()
        try:
            first_page.goto(platform_url, wait_until="domcontentloaded", timeout=30_000)
        except Exception:
            pass

        try:
            last_saved = 0.0
            while context.pages:
                now = time.monotonic()
                if now - last_saved > 2:
                    try:
                        _write_cookies_txt(context.cookies(), platform_cookie_file(platform))
                        _merge_cookie_files()
                        last_saved = now
                    except Exception:
                        pass
                time.sleep(0.5)
            _write_cookies_txt(context.cookies(), platform_cookie_file(platform))
            _merge_cookie_files()
        except Exception:
            return
        try:
            context.close()
        except Exception:
            pass


def launch_login_browser(platform: str) -> None:
    """用独立进程打开登录窗口，让主软件关闭后登录浏览器仍可保留。"""
    if platform not in {"douyin", "youtube"}:
        raise RuntimeError("未知的登录平台。")
    if not find_browser_path():
        raise RuntimeError("没有找到 Chrome 或 Edge，无法打开软件内登录窗口。")

    if getattr(sys, "frozen", False):
        command = [sys.executable, "--login-browser", platform]
        cwd = str(Path(sys.executable).resolve().parent)
    else:
        start_script = Path(__file__).resolve().parents[1] / "start.py"
        command = [sys.executable, str(start_script), "--login-browser", platform]
        cwd = str(start_script.parent)

    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS

    subprocess.Popen(
        command,
        cwd=cwd,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        close_fds=True,
        creationflags=creationflags,
    )


def _load_browser_cookies() -> list[dict[str, Any]]:
    from playwright.sync_api import sync_playwright

    browser_path = find_browser_path()
    if not browser_path:
        raise RuntimeError("没有找到 Chrome 或 Edge，无法读取软件内登录态。")

    with sync_playwright() as playwright:
        context = playwright.chromium.launch_persistent_context(
            user_data_dir=str(auth_profile_dir()),
            executable_path=browser_path,
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
            locale="zh-CN",
            user_agent=USER_AGENT,
        )
        cookies = context.cookies(
            [
                "https://www.douyin.com/",
                "https://www.iesdouyin.com/",
                "https://www.youtube.com/",
                "https://youtube.com/",
                "https://www.google.com/",
            ]
        )
        context.close()
    return cookies


def cookie_jar_from_auth_profile() -> http.cookiejar.CookieJar:
    if platform_cookie_file("douyin").exists() or platform_cookie_file("youtube").exists():
        _merge_cookie_files()
    cookie_file = auth_cookie_file()
    if cookie_file.exists():
        jar = http.cookiejar.MozillaCookieJar(str(cookie_file))
        jar.load(ignore_discard=True, ignore_expires=True)
        return jar

    jar = http.cookiejar.CookieJar()
    for item in _load_browser_cookies():
        domain = item.get("domain") or ""
        if not domain:
            continue
        cookie = http.cookiejar.Cookie(
            version=0,
            name=str(item.get("name") or ""),
            value=str(item.get("value") or ""),
            port=None,
            port_specified=False,
            domain=domain,
            domain_specified=domain.startswith("."),
            domain_initial_dot=domain.startswith("."),
            path=str(item.get("path") or "/"),
            path_specified=True,
            secure=bool(item.get("secure")),
            expires=int(item["expires"]) if item.get("expires") else None,
            discard=not bool(item.get("expires")),
            comment=None,
            comment_url=None,
            rest={},
            rfc2109=False,
        )
        jar.set_cookie(cookie)
    return jar


def export_auth_cookies_txt() -> Path:
    if platform_cookie_file("douyin").exists() or platform_cookie_file("youtube").exists():
        return _merge_cookie_files()
    cookie_file = auth_cookie_file()
    if cookie_file.exists():
        return cookie_file
    return _write_cookies_txt(_load_browser_cookies(), cookie_file)
